### ISSUE TITLE
Buildings that can use a size fix in the future.

### ISSUE THREAD

**Issue by Nexela** [pyanodon/pYCoalprocesing#15]
Meth, Power, Quench, Tar, Distil All need +1 X tile (east-west)

HPF needs +2 X tiles (east-west)

These changes will allow for a "square" base and the ability to walk behind the buildings for a sense of depth.

**Comment by pyanodon** [comment]
You mean add a transparent tile in left and right sides of the buildings? 

![doubt-01](https://cloud.githubusercontent.com/assets/22332428/19032604/19a4f36a-8931-11e6-9d3e-96e5cd1ca375.jpg)

**Comment by Nexela** [comment]
Hmm I think I put that backwards Would need be to be shrunk on the X (or increased 1 on the y)

So the "base" on the ground is x tiles wide and x tiles tall   Where tiles is an odd number for ease of things like rotating/blueprinting


![19a4f36a-8931-11e6-9d3e-96e5cd1ca375](https://cloud.githubusercontent.com/assets/13972192/19033604/374056f2-892d-11e6-8ea4-06368ca55ecf.jpg)

**Comment by Nexela** [comment]
Would look something along the lines of this 
![19a4f36a-8931-11e6-9d3e-96e5cd1ca375](https://cloud.githubusercontent.com/assets/13972192/19033849/92ce112a-892e-11e6-9fb6-d2a331c1768b.jpg)

**Comment by pyanodon** [comment]
Ohhhhh ok. I got it... Man... it will need a lot of time to remade everything and some adjustments on shifts will be needed too since every time i re-render a building, ver my little changes in pixel sizes happens. I think we should launch the mod when ready and them i will updating the old buildings at will while you work over the blue science tier.

**Comment by Nexela** [comment]
That is exactly what I was thinking.  However an upcoming change in .14.13 might mean we don't even have to do this. I will let you know when I play around with it.

**Comment by Nexela** [comment]
Moved to projects
