### ISSUE TITLE
Pollution and Power from Turbines

### ISSUE THREAD

**Issue by Nexela** [pyanodon/pYCoalprocesing#16]
What kind of range do we want for power and pollution with the turbines.

MK01 with syngas
MK01 with refsyngas?
MK01 with combustible"?

**Comment by pyanodon** [comment]
Yes...as well as MK02 with both... and MK03 too.. The differences between them will be the efficiency, consumption and pollution generated.

Also, if possible, the possibility to add more fuel types later (such burn "waste" or low grade residues for a complete pollution mess)

**Comment by Nexela** [comment]
Anything is possible!  just let me know the kind of numbers you are thinking for them

**Comment by pyanodon** [comment]
Here the idea i have of all the fuels made in this mod. (but of course, with the progress and other mods by our team new fuels can be added/removed at will. Each turbine would have that pollution and efficiency values (they already have, isnt?) , and depending of the fuel that is give to them, they burn in different ways as the upper part of the table.

  And just for fun, not a priority here, just a crazy idea after implemented the main part. Some of them could have a chance of destroy the turbine in a explosion, like you put super critical coal fuel into a MK01 turbine and running it at maximum consumption could have a chance of boom, you lost a turbine. hahaha..

![table](https://cloud.githubusercontent.com/assets/22332428/19038384/aa3dc68e-8951-11e6-9f2c-bfb79baa1660.jpg)

**Comment by Nexela** [comment]
--return the desired temperature based on efficiency
--100 is max temp get the remainder of the machines efficiency from max temp and adjust for fluids eff.
  return (100 - (100 - machine_eff) + eff)

Some values from your spreadsheet had to be adjusted
turbinemk01 has 50% efficiency, and syngas has an efficiency modifier of 0 then the turbine should put out 50% of it's maximum. And would cause turbine_pollution+fluid_pollution_modifier

Pollution code does need some more tweaking.

turbinemk01 has 50% efficiency and refsyngas has +3 modifier output 53% of maximum

Obviously these numbers can be tweaked a bit.

With the current code a mk04 turbine has 70% efficiency, using ultra-coal would add +20 efficiency making it run at 90% of maximum

The big question is what should the theoretical maximum power output in MW be for each turbine

**Comment by pyanodon** [comment]
Actually, that´s a very clever question.. Lets set it up.  Feel free to suggest and adjust values my friend. That table was just a starting thing.

Lets try:

MK01 = 2MW
MK02 = 4MW
MK03 = 6MW
MK04 = 8MW

Increments of 2Mw should attend the demands of the game and pair with the technology advances.

**Comment by Nexela** [comment]
Hmm looking at it I think 2^Turbine level might make for better values to work with.

Lemme see if I can get a spreadsheet going to look it over better.

**Comment by Nexela** [comment]
https://docs.google.com/spreadsheets/d/1UVIatc7TxhIlOoL4XklFnZY1TgQvYXxsHgwH3qxwDUc/edit?usp=sharing

**Comment by pyanodon** [comment]
I cant edit the sheet.  Anyway,  i made a test here in the recent pre-release and noticed the turbines output almost the same amount of power whatever fuel we put on them at maximum usage. I dunno if this mode are working or added in the mod, but for example, when i put combustion mixture 1 to MK02 turbine, it gave me a 5,6-5.7 Max, when put refined syngas, this number increased a bit to 5.9. Methanol made no difference. With MK01, the turbine also burned better with a lower class fuel such refined syngas, combustion mixture and methanol gave it less performance.  Since there´s differences, i imagine the mode is working, but we should increase the discrepancy between the fuels.

**Comment by Nexela** [comment]
Somehow I missed your last comment. 

I agree that while it is "working" the range needs to be adjusted some.  Possibly by doubling at the maximum.  Also remember that "pollution" goes down using better fluids/machines too

The sheet should be editable now.

**Comment by pyanodon** [comment]
No problem mate! 

I agree it may be only a matter of re-do some numbers. And yes, the sheet is editable now. Thanks!

**Comment by pyanodon** [comment]
Updated the sheet. Now is time to crunch some numbers to make it expressive in the game :D

**Comment by Nexela** [comment]
Moved to project board

**Comment by Nexela** [comment]
OMG, spend a couple of hours on this the other day and couldn't figure out why Methanol was creating a lot more energy then everything else......
Turns out I didn't notice this in the fluid definition. heat_capacity = "3KJ",
Gonna try and push out another pre-release this weekend with working and consistent fuel values!

**Comment by Nexela** [comment]
Also possibly bumping up the values a bit for max power to have a better spread

Off to see if heat_capacity is available in the game.prototypes!

**Comment by pyanodon** [comment]
Oh,that´s great. So, we can change the values of each fuel by changing their heat_capacity value? That would turn the balance things more easier for future and even the addition of new fuels.

But there´s that problem, if the turbines generates energy based on that, are you sure we CANNOT run turbines with vanilla steam?

**Comment by Nexela** [comment]
It might play a role in it.  or I might set methanol to 1 and forget about it :)   it but the overall scripting is still needed to generate the correct heat levels. Otherwise water would generate power if it was sent in already heated.

Or we go through all liquids and assign a value to them but this could also mean changing base and or mod values from other fluids (pet gas, light oil) which I like to typically avoid as other mods could be depending on those values too.

**Comment by pyanodon** [comment]
Sounds reasonable, lets not change the vanilla fluids...but still there´s a way to make pet gas light oil usable in these turbines?

**Comment by pyanodon** [comment]
Hello! Is it possible to add Hydrogen as fuel too? IT would be a nice addition  since in both big mods like Bob´s and Angels Hydrogen is like a issue to always have excess of them. And it´s great fuel with no pollution.  If you want, i can add in that sheet some data to turn hydrogen an good option to burn.

**Comment by Nexela** [comment]
Sure. Pop some numbers in the sheet!

**Comment by pyanodon** [comment]
Ok! I updated the sheet. Organized things and updated values :)
