### ISSUE TITLE
Tailings pond Animation sheet

### ISSUE THREAD

**Issue by Nexela** [pyanodon/pYCoalprocesing#3]
Slight wiggle-waggle with the underground pipe portion when cycling through animations

**Comment by pyanodon** [comment]
Oh?? I will check it out.

**Comment by pyanodon** [comment]
![tailings-problem](https://cloud.githubusercontent.com/assets/22332428/19176453/57814494-8c16-11e6-8c92-e4e13c790d22.png)

You mean with this guy?

**Comment by Nexela** [comment]
It was a booboo on my part, I think I have all the raw files I just need to get around to fixing them. but before I do that I want to hear rseddings reply on pipe_picture for storage tank/generators

**Comment by Nexela** [comment]
What do you think of this?

![meh](https://cloud.githubusercontent.com/assets/13972192/19212966/290d5dec-8d2d-11e6-86f8-0ae1d50dada0.png)

Also I Should have gassifier pipe connections done tonight.

**Comment by pyanodon** [comment]
Way better than i expected!! Also, clever, we need a pump to extract that 👍

**Comment by Nexela** [comment]
Awesome will have it finished this weekend then!

**Comment by Nexela** [comment]
Closed with commit #2a10482afcd8cb80dc2d421ff75a907b6c5e4ca6
