### ISSUE TITLE
Subgroup must be defined when there is no common main product

### ISSUE THREAD

**Issue by Neal248** [pyanodon/pYCoalprocesing#43]
30.781 Mods to disable:Failed to load mods: Error while running setup for recipe prototype "advanced-foundry-gas-separation" (recipe): Subgroup must be defined when there is no common main product.

**Comment by Nexela** [comment]
List of mods you have installed?

**Comment by Neal248** [comment]
I play with more but it also occurs with these...
<img width="207" alt="bildschirmfoto 2017-08-02 um 18 07 28" src="https://user-images.githubusercontent.com/29894392/28883127-b309b728-77ad-11e7-9d5c-64ecc42a7e95.png">

**Comment by Neal248** [comment]
Ok I think its related to Bio_Industries...
