### ISSUE TITLE
Why is creosote a recipe ingredient for medium steel power poles??

### ISSUE THREAD

**Issue by ChurchOrganist** [pyanodon/pYCoalprocesing#46]
Creosote is a wood preservative - so why on earth have you changed the medium steel power pole recipe to include it as an ingredient?????

I appreciate this is Factorio, but recipes should bear some resemblance to real life.

The only effect painting steel power poles with creosote would have is to make a nasty sticky mess, and poison the area around it!

It would have no preservative effect whatsoever!

Maybe add a second wooden power pole with more reach/area researchable with red science?

**Comment by pyanodon** [comment]
We re sorry you doesnt like it. These poles use wood,  so we will use creosote.

**Comment by ChurchOrganist** [comment]
Check the recipe! - the medium power poles use steel!!!
