### ISSUE TITLE
Turbine Image enhancments

### ISSUE THREAD

**Issue by Nexela** [pyanodon/pYCoalprocesing#5]
Then animation sheets for the mko1 turbine need a bit of rework.

1. We have access to "smoke", I recommend removing the fake smoke from the animation sheet. (if it runs out of syngas mid frame the picture will be stuck showing smoke)
2. Vertical Sheet - Needs a better pipe ending. Something like a doghouse type bump out that connects to the base. right now the pipe "connects" to the middle of the tube and looks weird.
3. Horizontal Sheet - Would need the same kind of thing on the east/west portions for pipe connection.
4. Possibly scale both sheets up %40 to avoid scaling issues with pipe connections.

**Comment by pyanodon** [comment]
Hummm got it! i will start to working on it as soon as i finish the MK02 turbine which im working now.

in the 4º item.. you means to increase the whole sheet in 40%? Factorio have a limit of 2048x2048px for textures.

**Comment by Nexela** [comment]
Hmm might be better off waiting on the resizing then.  as long as there is a custom south pipe cover it should be ok.

**Comment by pyanodon** [comment]
Ok! i will come up with some idea soon.

**Comment by pyanodon** [comment]
![fixes](https://cloud.githubusercontent.com/assets/22332428/19089998/f32fe604-8a52-11e6-9bcd-c190e0b5aa29.jpg)
 Something like that would solve it?

**Comment by Nexela** [comment]
yes but they need to separated

The vertical.png would only show the "front" part.  and the other sheet would only show the horizontal part.

![vert-hori](https://cloud.githubusercontent.com/assets/13972192/19090470/a35c3dcc-8a4c-11e6-8c20-f4817fcef80e.png)

**Comment by pyanodon** [comment]
Ok!

**Comment by Nexela** [comment]
Did I mention how awesome the turbine looks!   Fixed up the pipe connections the best I could. Had to shift the image around but I think it looks great.

![hotdongs](https://cloud.githubusercontent.com/assets/13972192/19212694/9b967e92-8d24-11e6-86ef-7e6a91976f54.png)

**Comment by pyanodon** [comment]
That came out really great!! I love the final results too, is so nice to see it working :3  I will need to work hard here to produce a MK03 and MK04 in the same level ahaha.
