### ISSUE TITLE
Assembly Machine type entities

### ISSUE THREAD

**Issue by Nexela** [pyanodon/pYCoalprocesing#6]
These entities don't need the pipe stubs, they can be added using "pipe_pictures"

**Comment by pyanodon** [comment]
Man....what you did with the connection pipes...was..just...amazing!  I cant thank you enough for that ahaha. I will remove the stubs of all of them (the assemblies)!

**Comment by Nexela** [comment]
You can even modify the endings to fit better with your theme, just copy from the base gfx
