### ISSUE TITLE
PIPES - Carbon Filter

### ISSUE THREAD

**Issue by Nexela** [pyanodon/pYCoalprocesing#7]
Needs adjustments for pipes., possibly allow adjustment of building to allow rotation?

**Comment by pyanodon** [comment]
Yes... i will re-do some parts of it to allow the new pipes connections on it. But first, i will solve that small problem in the MK01 turbine graphics.

**Comment by Nexela** [comment]
No problem, I just find it easier to keep track of what needs to be done by using issues.
